// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQuery(arg1, arg2) {
  return window['go']['main']['App']['CancelQuery'](arg1, arg2);
}

export function ConfigDir() {
  return window['go']['main']['App']['ConfigDir']();
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function ConnectedIDs() {
  return window['go']['main']['App']['ConnectedIDs']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function Explain(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Explain'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportCSV(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportCSV'](arg1, arg2, arg3);
}

export function FunctionDefinition(arg1, arg2) {
  return window['go']['main']['App']['FunctionDefinition'](arg1, arg2);
}

export function InstallStatStatements(arg1) {
  return window['go']['main']['App']['InstallStatStatements'](arg1);
}

export function ListColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListColumns'](arg1, arg2, arg3);
}

export function ListFunctions(arg1, arg2) {
  return window['go']['main']['App']['ListFunctions'](arg1, arg2);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListRelations(arg1, arg2) {
  return window['go']['main']['App']['ListRelations'](arg1, arg2);
}

export function ListSchemas(arg1) {
  return window['go']['main']['App']['ListSchemas'](arg1);
}

export function RelationInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['RelationInfo'](arg1, arg2, arg3);
}

export function ResetStatStatements(arg1) {
  return window['go']['main']['App']['ResetStatStatements'](arg1);
}

export function RunQuery(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunQuery'](arg1, arg2, arg3, arg4);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2);
}

export function StatStatements(arg1, arg2, arg3) {
  return window['go']['main']['App']['StatStatements'](arg1, arg2, arg3);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}
