// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {config} from '../models';
import {spec} from '../models';

export function ActivitySampling(arg1:string):Promise<db.SamplingStatus>;

export function CancelQuery(arg1:string,arg2:string):Promise<boolean>;

export function ConfigDir():Promise<string>;

export function Connect(arg1:string,arg2:string):Promise<db.Info>;

export function ConnectedIDs():Promise<Array<string>>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function Explain(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<db.ExplainResponse>;

export function ExportCSV(arg1:Array<string>,arg2:Array<any>,arg3:string):Promise<string>;

export function FunctionDefinition(arg1:string,arg2:number):Promise<string>;

export function InstallStatStatements(arg1:string):Promise<void>;

export function ListColumns(arg1:string,arg2:string,arg3:string):Promise<Array<db.ColumnInfo>>;

export function ListFunctions(arg1:string,arg2:string):Promise<Array<db.Routine>>;

export function ListProfiles():Promise<Array<config.Profile>>;

export function ListRelations(arg1:string,arg2:string):Promise<Array<db.Relation>>;

export function ListSchemas(arg1:string):Promise<Array<db.Schema>>;

export function QueryExamples(arg1:string,arg2:string):Promise<Array<db.QueryExample>>;

export function RelationInfo(arg1:string,arg2:string,arg3:string):Promise<db.RelationInfo>;

export function RenderDiagram(arg1:spec.Graph,arg2:string):Promise<string>;

export function ResetStatStatements(arg1:string):Promise<void>;

export function RunQuery(arg1:string,arg2:string,arg3:string,arg4:number):Promise<db.QueryResponse>;

export function SaveProfile(arg1:config.Profile,arg2:string):Promise<config.Profile>;

export function StartActivitySampling(arg1:string):Promise<void>;

export function StatStatements(arg1:string,arg2:boolean,arg3:number):Promise<db.StatsResponse>;

export function StopActivitySampling(arg1:string):Promise<void>;

export function TestConnection(arg1:config.Profile,arg2:string):Promise<string>;

export function Version():Promise<string>;
